export const OPAMP = {
  steps: [
    {
      id: "real",
      view: "opreal",
      highlight: "all",
      title: "A real op-amp",
      boardHint: "The triangle is a VCVS. vo = A(vp − vn).",
      body: "An op-amp is a voltage-controlled voltage source used for amplification. A real package (for example a 741) has many pins; we will not draw all of them.",
      check: {
        prompt: "The triangle is modeled as",
        options: {
          a: "A current source of value $A$.",
          b: "A VCVS: $v_o=A(v_p-v_n)$.",
          c: "Two independent batteries.",
        },
        answer: "b",
        why: "Open-loop gain $A$ multiplies the difference of the two input voltages.",
      },
    },
    {
      id: "ideal",
      view: "opideal",
      highlight: "all",
      title: "Ideal op-amp",
      boardHint: "A → ∞, Ri → ∞, Ro = 0.",
      body: "Treat it like a cleaned-up equivalent: infinite gain, infinite input resistance, zero output resistance. Finite $v_o$ then forces the two input currents to zero and the two input voltages to match.",
      eq: [
        "$$A\\to\\infty,\\quad R_i\\to\\infty,\\quad R_o=0$$",
        "$$i_p=i_n=0$$",
        "$$v_p=v_n$$",
      ],
      check: {
        prompt: "Ideal $R_o$ is",
        options: {
          a: "$\\infty$, so no current can leave the output.",
          b: "$0$, so the output looks like an ideal voltage source.",
          c: "Equal to $R_i$.",
        },
        answer: "b",
        why: "$R_i\\to\\infty$ kills input current. $R_o=0$ is the output. Do not swap them.",
      },
    },
    {
      id: "whyA",
      view: "feedback",
      highlight: "a",
      title: "Why not freeze $A$ at a large number?",
      boardHint: "A is the left block. Feedback is what you trust, not the exact A.",
      points: [
        "If $A=\\infty$ with no feedback, $v_o$ is not usable.",
        "$A$ is poorly controlled from chip to chip.",
        "Negative feedback makes $v_o/v_{in}$ depend on the network around the amp, not on the exact $A$.",
      ],
      check: {
        prompt: "We still write $A\\to\\infty$ instead of locking $A=10^5$ because",
        options: {
          a: "Every 741 has $A$ guaranteed at exactly $10^5$.",
          b: "Chip-to-chip $A$ is sloppy. Negative feedback makes the gain depend on the resistors.",
          c: "Infinite $A$ forces $v_o=0$.",
        },
        answer: "b",
        why: "Closed-loop gain heads toward $1/\\beta$, which you set with the network, not the datasheet $A$.",
      },
    },
    {
      id: "loop",
      view: "feedback",
      highlight: "beta",
      title: "Under negative feedback",
      boardHint: "The middle block is −β. Closed-loop gain heads toward 1/β.",
      body: "A fraction $\\beta$ of the output is subtracted at the input. Closed-loop gain heads toward $1/\\beta$ when $A$ is large. Feedback goes to the minus pin so the loop stays negative.",
      eq: [
        "$$(v_{in}-\\beta v_o)A=v_o$$",
        "$$\\dfrac{v_o}{v_{in}}=\\dfrac{A}{1+A\\beta}\\;\\to\\;\\dfrac{1}{\\beta}$$",
      ],
      check: {
        prompt: "$\\beta=0.25$ and $A$ is huge. $v_o/v_{in}$ is about",
        options: {
          a: "$0.25$.",
          b: "$4$.",
          c: "$10^{5}$.",
        },
        answer: "b",
        why: "$1/\\beta=4$. $0.25$ is $\\beta$ itself. $10^{5}$ is a typical open-loop $A$ — that is what feedback removes.",
      },
    },
  ],
  practice: [
    {
      id: "p1",
      view: "opideal",
      highlight: "all",
      boardHint: "Ri → ∞, so the input pins do not draw current.",
      prompt: "Ideal input currents $i_p$ and $i_n$ are",
      options: {
        a: "$v_o/R_o$.",
        b: "$0$.",
        c: "Infinite.",
      },
      answer: "b",
      why: "$R_i\\to\\infty$. Current into either pin is zero. $v_o/R_o$ would be an output-side guess.",
    },
    {
      id: "p2",
      view: "opideal",
      highlight: "all",
      boardHint: "vo = A(vp − vn). A is huge and vo is finite.",
      prompt: "Finite $v_o$ with $A\\to\\infty$ forces $v_p-v_n$ to",
      options: {
        a: "$0$.",
        b: "$v_o$.",
        c: "$1\\,\\mathrm{V}$.",
      },
      answer: "a",
      why: "$v_o=A(v_p-v_n)$. Infinite $A$ and a usable $v_o$ means the difference must vanish: $v_p=v_n$. It is not $1\\,\\mathrm{V}$ and not $v_o$.",
    },
    {
      id: "p3",
      view: "opideal",
      highlight: "all",
      boardHint: "The middle box is Ri. Infinite Ri means no pin current.",
      prompt: "Ideal $R_i$ is",
      options: {
        a: "$0$, so the two pins short together.",
        b: "$\\infty$, so the pins draw no current.",
        c: "Equal to $R_o$.",
      },
      answer: "b",
      why: "Infinite input resistance: $i_p=i_n=0$. Zero would have been $R_o$.",
    },
    {
      id: "p4",
      view: "feedback",
      highlight: "beta",
      boardHint: "Closed-loop gain heads toward 1/β, not β and not a datasheet open-loop number.",
      prompt: "$\\beta=1/5$ and $A$ is large. Closed-loop $v_o/v_{in}$ is about",
      options: {
        a: "$5$.",
        b: "$1/5$.",
        c: "$10^{5}$.",
      },
      answer: "a",
      why: "$1/\\beta=5$. $1/5$ is $\\beta$ itself. $10^{5}$ is a typical open-loop $A$, which feedback replaces.",
    },
    {
      id: "p5",
      view: "opideal",
      highlight: "all",
      boardHint: "Ro is the small box on the output side.",
      prompt: "Ideal output resistance $R_o$ is",
      options: {
        a: "Infinite, like an open.",
        b: "Equal to $R_i$.",
        c: "$0$, so $v_o$ is a stiff voltage.",
      },
      answer: "c",
      why: "$R_o=0$ means the output looks like an ideal voltage source. Infinite would have been $R_i$.",
    },
  ],
};

export const INVERTING = {
  steps: [
    {
      id: "pic",
      view: "inv",
      highlight: "all",
      title: "Inverting configuration",
      body: "Input through $R_1$ into the minus pin. Feedback $R_2$ from output to minus. Plus pin at ground. Feedback is negative.",
    },
    {
      id: "kcl",
      view: "inv",
      highlight: "kcl",
      title: "KCL at the minus pin",
      body: "Ideal: $i_n=0$ and $v_n=v_p=0$ (virtual ground). Current in $R_1$ equals current in $R_2$.",
      eq: [
        "$$\\dfrac{v_{in}-0}{R_1}=\\dfrac{0-v_o}{R_2}$$",
        "$$\\dfrac{v_o}{v_{in}}=-\\dfrac{R_2}{R_1}$$",
      ],
      check: {
        prompt: "Inverting closed-loop gain is",
        options: {
          a: "$-R_2/R_1$.",
          b: "$1+R_2/R_1$.",
          c: "$-A$.",
        },
        answer: "a",
        why: "Sign flip because the minus pin is the summing node. Non-inverting is $1+R_f/R_g$.",
      },
    },
    {
      id: "beta",
      view: "inv",
      highlight: "fb",
      title: "Same idea as $1/\\beta$",
      body: "You can also write KCL without assuming $A=\\infty$ first, then take $A\\to\\infty$. The resistors set $\\beta$, and the gain settles to $-R_2/R_1$.",
    },
  ],
  practice: [
    {
      id: "p1",
      view: "inv",
      highlight: "all",
      prompt: "$R_1=2\\,\\mathrm{k}\\Omega$, $R_2=10\\,\\mathrm{k}\\Omega$. $v_o/v_{in}$ is",
      options: {
        a: "$-5$.",
        b: "$6$.",
        c: "$-1/5$.",
      },
      answer: "a",
      why: "$-10/2=-5$.",
    },
    {
      id: "p2",
      view: "inv",
      highlight: "all",
      prompt: "On the inverting amp, the minus pin is a virtual ground, so $v_n$ is",
      options: {
        a: "$v_{in}$.",
        b: "$0$.",
        c: "$v_o$.",
      },
      answer: "b",
      why: "Plus is grounded, so $v_p=0$. Virtual short copies that: $v_n=0$.",
    },
    {
      id: "p3",
      view: "inv",
      highlight: "all",
      prompt: "The plus pin of the inverting amp is wired to",
      options: {
        a: "$v_{in}$.",
        b: "$v_o$.",
        c: "Ground.",
      },
      answer: "c",
      why: "Non-inverting pin at $0$. Feedback $R_2$ goes to the minus pin, not the plus.",
    },
    {
      id: "p4",
      view: "inv",
      highlight: "kcl",
      prompt: "Ideal $i_n=0$, so the current through $R_1$ compared with $R_2$ is",
      options: {
        a: "Twice as large.",
        b: "The same.",
        c: "Zero in $R_2$.",
      },
      answer: "b",
      why: "No current enters the pin, so KCL says $i_{R_1}=i_{R_2}$.",
    },
    {
      id: "p5",
      view: "inv",
      highlight: "all",
      prompt: "$R_1=4\\,\\mathrm{k}\\Omega$, $R_2=4\\,\\mathrm{k}\\Omega$. $v_o/v_{in}$ is",
      options: {
        a: "$1$.",
        b: "$2$.",
        c: "$-1$.",
      },
      answer: "c",
      why: "$-R_2/R_1=-1$. Equal resistors still invert.",
    },
  ],
};

export const NONINV = {
  steps: [
    {
      id: "pic",
      view: "ninv",
      highlight: "all",
      title: "Non-inverting configuration",
      body: "Input at the plus pin. A divider $R_1$, $R_2$ from output to ground feeds the minus pin. Output has the same sign as the input.",
    },
    {
      id: "gain",
      view: "ninv",
      highlight: "div",
      title: "Divider sets $\\beta$",
      body: "Virtual short: $v_n=v_{in}$. The divider is $R_1/(R_1+R_2)$, so $\\beta=R_1/(R_1+R_2)$ and $1/\\beta=1+R_2/R_1$.",
      eq: [
        "$$\\beta=\\dfrac{R_1}{R_1+R_2}$$",
        "$$\\dfrac{v_o}{v_{in}}=1+\\dfrac{R_2}{R_1}$$",
      ],
      check: {
        prompt: "If $R_2=0$ (output shorted to minus), the gain is",
        options: {
          a: "$1$ (buffer).",
          b: "$0$.",
          c: "Infinite.",
        },
        answer: "a",
        why: "$1+0=1$. Voltage follower.",
      },
    },
  ],
  practice: [
    {
      id: "p1",
      view: "ninv",
      highlight: "all",
      prompt: "Non-inverting gain with $R_2=9\\,\\mathrm{k}\\Omega$, $R_1=1\\,\\mathrm{k}\\Omega$ is",
      options: {
        a: "$10$.",
        b: "$-9$.",
        c: "$9$.",
      },
      answer: "a",
      why: "$1+9/1=10$. Inverting would have been $-9$.",
    },
    {
      id: "p2",
      view: "ninv",
      highlight: "all",
      prompt: "On the non-inverting amp, $v_{in}$ is applied at",
      options: {
        a: "The minus pin through $R_1$.",
        b: "The plus pin.",
        c: "The output node.",
      },
      answer: "b",
      why: "Signal goes to $+$. The divider $R_1$, $R_2$ feeds the minus pin.",
    },
    {
      id: "p3",
      view: "ninv",
      highlight: "div",
      prompt: "If $R_2=0$ (a wire from $v_o$ to minus), the gain is",
      options: {
        a: "$0$.",
        b: "Infinite.",
        c: "$1$ (buffer).",
      },
      answer: "c",
      why: "$1+R_2/R_1=1$. Voltage follower.",
    },
    {
      id: "p4",
      view: "ninv",
      highlight: "all",
      prompt: "$R_2=3\\,\\mathrm{k}\\Omega$, $R_1=1\\,\\mathrm{k}\\Omega$. Non-inverting $v_o/v_{in}$ is",
      options: {
        a: "$-3$.",
        b: "$4$.",
        c: "$3$.",
      },
      answer: "b",
      why: "$1+3/1=4$. $-3$ is the inverting mix-up. $3$ forgot the $1+$.",
    },
    {
      id: "p5",
      view: "ninv",
      highlight: "div",
      prompt: "The divider from $v_o$ to ground sets $\\beta$. Then closed-loop gain is about",
      options: {
        a: "$\\beta$.",
        b: "$1/\\beta=1+R_2/R_1$.",
        c: "$-R_2/R_1$.",
      },
      answer: "b",
      why: "$\\beta=R_1/(R_1+R_2)$, so $1/\\beta=1+R_2/R_1$. The minus form is inverting.",
    },
  ],
};

export const CAPACITOR = {
  steps: [
    {
      id: "freq",
      view: "cap",
      highlight: "all",
      title: "Not just DC",
      body: "Until now sources were constant. A capacitor cares about how voltage changes with time — it is frequency-dependent.",
      check: {
        prompt: "Capacitor current depends on",
        options: {
          a: "How fast the voltage is changing, not only the present $v$.",
          b: "Only the present voltage, like a resistor.",
          c: "Only the battery $V_s$, never $dv/dt$.",
        },
        answer: "a",
        why: "A resistor is $v=Ri$. A capacitor is $i=C\\,dv/dt$, so a constant voltage means zero current.",
      },
    },
    {
      id: "vsr",
      view: "cap",
      highlight: "c",
      title: "Capacitor vs resistor",
      body: "Parallel plates: $C=\\varepsilon A/d$ and $q=Cv$. Current is the rate of charge.",
      eq: [
        "$$i=dq/dt=C\\,dv/dt$$",
        "$$v(t)=v(t_0)+\\dfrac{1}{C}\\int_{t_0}^{t} i(t')\\,dt'$$",
      ],
      check: {
        prompt: "If the voltage on $C$ is not changing, $i$ is",
        options: {
          a: "$0$.",
          b: "$Cv$.",
          c: "Infinite.",
        },
        answer: "a",
        why: "$i=C\\,dv/dt$. If $dv/dt=0$, current is zero. That is why C becomes an open in DC.",
      },
    },
    {
      id: "dcopen",
      view: "capopen",
      highlight: "all",
      title: "Replace C with an open",
      boardHint: "Top picture still has C. Bottom picture is the same loop with C removed (a gap).",
      body: [
        "Look at the two pictures. Both have the same battery $V_s$ and the same resistor $R$.",
        "Top: the capacitor is still in the loop. Current can flow while the voltage is changing.",
        "Bottom: a long time after $t=0$, the voltage has stopped changing. Then $i=C\\,dv/dt=0$, so we erase $C$ and leave a gap — an open circuit.",
      ],
      eq: "$$t>0:\\ C\\ \\to\\ \\text{open},\\quad i=0$$",
      check: {
        prompt: "For $t>0$ in DC, a capacitor acts like",
        options: {
          a: "An open circuit (a gap, no current).",
          b: "A short circuit (a wire).",
          c: "A resistor $C$.",
        },
        answer: "a",
        why: "Voltage has settled, so $dv/dt=0$ and $i=0$. Draw a break in the wire where C was.",
      },
    },
    {
      id: "energy",
      view: "cap",
      highlight: "w",
      title: "Power and energy",
      points: [
        "Energy stored: $w=\\tfrac{1}{2} C v^2$.",
        "Power is $p=vi=Cv\\,dv/dt$.",
      ],
      eq: [
        "$$p=vi=Cv\\,dv/dt$$",
        "$$w=\\tfrac{1}{2}Cv^2$$",
      ],
      check: {
        prompt: "If you double the voltage on a capacitor, stored energy",
        options: {
          a: "Quadruples, because $w\\propto v^2$.",
          b: "Doubles, because $w\\propto v$.",
          c: "Stays the same — energy depends only on $C$.",
        },
        answer: "a",
        why: "$w=\\tfrac12 C v^2$. Twice the voltage is four times the energy.",
      },
    },
    {
      id: "eq",
      view: "cap",
      highlight: "eq",
      title: "Series and parallel",
      boardHint: "Left: C1 and C2 in one loop (series). Right: C1 and C2 share both ends (parallel).",
      eq: [
        "$$\\text{series: } C_{eq}=\\left(\\dfrac{1}{C_1}+\\dfrac{1}{C_2}\\right)^{-1}$$",
        "$$\\text{parallel: } C_{eq}=C_1+C_2$$",
      ],
      body: "Series share current (like resistors in parallel). Parallel share voltage (like resistors in series — inverted).",
      check: {
        prompt: "Two equal capacitors in series make $C_{eq}$",
        options: {
          a: "Half of one of them.",
          b: "Twice one of them.",
          c: "The same as one of them.",
        },
        answer: "a",
        why: "Series: $1/C_{eq}=1/C+1/C$, so $C_{eq}=C/2$. Parallel would have been $2C$.",
      },
    },
  ],
  practice: [
    {
      id: "p1",
      view: "cap",
      highlight: "c",
      boardHint: "Vs, R, and C in one loop. i through C, v across the plates.",
      prompt: "The defining capacitor law is",
      options: {
        a: "$i=C\\,dv/dt$.",
        b: "$v=C\\,di/dt$.",
        c: "$v=Ri$.",
      },
      answer: "a",
      why: "Inductor is $v=L\\,di/dt$.",
    },
    {
      id: "p2",
      view: "capopen",
      highlight: "all",
      boardHint: "Top still has C. Bottom is the same loop with a gap.",
      prompt: "A long time after a DC source is applied, the capacitor acts like",
      options: {
        a: "An open circuit (a gap, $i=0$).",
        b: "A short circuit (a wire).",
        c: "A resistor of value $C$.",
      },
      answer: "a",
      why: "Voltage has settled, so $dv/dt=0$ and $i=C\\,dv/dt=0$.",
    },
    {
      id: "p3",
      view: "cap",
      highlight: "w",
      boardHint: "Energy lives in the electric field between the plates.",
      prompt: "Energy stored in a capacitor is",
      options: {
        a: "$\\tfrac{1}{2} C v^2$.",
        b: "$\\tfrac{1}{2} C i^2$.",
        c: "$Cv$.",
      },
      answer: "a",
      why: "Inductor energy is $\\tfrac{1}{2} L i^2$. Capacitor energy uses voltage.",
    },
    {
      id: "p4",
      view: "cap",
      highlight: "eq",
      boardHint: "Left: one path through both (series). Right: two paths, same voltage (parallel).",
      prompt: "Two capacitors $C_1$ and $C_2$ in parallel have",
      options: {
        a: "$C_{eq}=C_1+C_2$.",
        b: "$C_{eq}=(1/C_1+1/C_2)^{-1}$ only.",
        c: "$C_{eq}=C_1 C_2$.",
      },
      answer: "a",
      why: "Parallel capacitors share voltage, so capacitance adds. Series uses the reciprocal sum.",
    },
    {
      id: "p5",
      view: "cap",
      highlight: "eq",
      boardHint: "Left: one path through both (series).",
      prompt: "Two capacitors $C_1$ and $C_2$ in series have",
      options: {
        a: "$C_{eq}=C_1+C_2$.",
        b: "$1/C_{eq}=1/C_1+1/C_2$.",
        c: "$C_{eq}=C_1 C_2$.",
      },
      answer: "b",
      why: "Series: same current, voltages add, so reciprocals of $C$ add. Parallel is $C_1+C_2$.",
    },
  ],
};

export const INDUCTOR = {
  steps: [
    {
      id: "vsr",
      view: "ind",
      highlight: "l",
      title: "Inductor vs resistor",
      body: "From flux linkage, $v=d\\Lambda/dt$ and $L=\\Lambda/i$. Memorize the circuit law, not the coil geometry.",
      eq: [
        "$$v=L\\,di/dt$$",
        "$$i(t)=i(t_0)+\\dfrac{1}{L}\\int_{t_0}^{t} v(t')\\,dt'$$",
      ],
      check: {
        prompt: "If the current through $L$ is not changing, $v$ is",
        options: {
          a: "$0$.",
          b: "$Li$.",
          c: "Infinite.",
        },
        answer: "a",
        why: "$v=L\\,di/dt$. If $di/dt=0$, voltage is zero. That is why L becomes a short in DC.",
      },
    },
    {
      id: "dcshort",
      view: "indshort",
      highlight: "all",
      title: "Replace L with a short",
      boardHint: "Top picture still has L. Bottom is the same loop with L replaced by a wire.",
      body: [
        "Look at the two pictures. Both have the same battery $V_s$ and the same resistor $R$.",
        "Top: the inductor is still in the loop. Voltage appears while the current is changing.",
        "Bottom: a long time after $t=0$, the current has stopped changing. Then $v=L\\,di/dt=0$, so we draw $L$ as a wire — a short circuit.",
      ],
      eq: "$$t>0:\\ L\\ \\to\\ \\text{short},\\quad i=V_s/R$$",
      check: {
        prompt: "For $t>0$ in DC, an inductor acts like",
        options: {
          a: "A short circuit (a wire). Current is $V_s/R$.",
          b: "An open circuit (a gap, no current).",
          c: "A capacitor $L$.",
        },
        answer: "a",
        why: "Current has settled, so $di/dt=0$ and $v=0$. Draw a wire where L was. Then $i=V_s/R$.",
      },
    },
    {
      id: "energy",
      view: "ind",
      highlight: "w",
      title: "Power and energy",
      points: [
        "If $i$ is constant, $v=0$: an inductor is a short circuit in DC steady state.",
        "Energy stored: $w=\\tfrac{1}{2} L i^2$.",
      ],
      eq: [
        "$$p=vi=Li\\,di/dt$$",
        "$$w=\\tfrac{1}{2}Li^2$$",
      ],
      check: {
        prompt: "In DC steady state an inductor acts like",
        options: {
          a: "A short circuit.",
          b: "An open circuit.",
          c: "A capacitor $L$.",
        },
        answer: "a",
        why: "$di/dt=0$ so $v=0$.",
      },
    },
    {
      id: "eq",
      view: "ind",
      highlight: "eq",
      title: "Series and parallel",
      boardHint: "Left: L1 and L2 in one loop (series). Right: L1 and L2 share both ends (parallel).",
      eq: [
        "$$\\text{series: } L_{eq}=L_1+L_2$$",
        "$$\\text{parallel: } L_{eq}=\\left(\\dfrac{1}{L_1}+\\dfrac{1}{L_2}\\right)^{-1}$$",
      ],
      body: "Series $L$ adds (shared current). Parallel $L$ is the reciprocal sum (shared voltage).",
      check: {
        prompt: "Two equal inductors in series make $L_{eq}$",
        options: {
          a: "Twice one of them.",
          b: "Half of one of them.",
          c: "The same as one of them.",
        },
        answer: "a",
        why: "Series: $L_{eq}=L+L=2L$. Parallel would have been $L/2$. Capacitors do the opposite.",
      },
    },
  ],
  practice: [
    {
      id: "p1",
      view: "ind",
      highlight: "l",
      boardHint: "Vs, R, and L in one loop. i through L, v across the coil.",
      prompt: "The defining inductor law is",
      options: {
        a: "$v=L\\,di/dt$.",
        b: "$i=L\\,dv/dt$.",
        c: "$v=Ri$.",
      },
      answer: "a",
      why: "Capacitor is $i=C\\,dv/dt$.",
    },
    {
      id: "p2",
      view: "indshort",
      highlight: "all",
      boardHint: "Top still has L. Bottom is the same loop with a wire.",
      prompt: "A long time after a DC source is applied, the inductor acts like",
      options: {
        a: "A short circuit (a wire). Current is $V_s/R$.",
        b: "An open circuit (a gap, $i=0$).",
        c: "A resistor of value $L$.",
      },
      answer: "a",
      why: "Current has settled, so $di/dt=0$ and $v=0$. Then only $R$ sets $i=V_s/R$.",
    },
    {
      id: "p3",
      view: "ind",
      highlight: "w",
      boardHint: "Energy lives in the magnetic field of the coil.",
      prompt: "Energy stored in an inductor is",
      options: {
        a: "$\\tfrac{1}{2} L i^2$.",
        b: "$\\tfrac{1}{2} L v^2$.",
        c: "$Li$.",
      },
      answer: "a",
      why: "Capacitor energy is $\\tfrac{1}{2} C v^2$. Inductor energy uses current.",
    },
    {
      id: "p4",
      view: "ind",
      highlight: "eq",
      boardHint: "Left: one path through both (series). Right: two paths, same voltage (parallel).",
      prompt: "Two inductors $L_1$ and $L_2$ in series have",
      options: {
        a: "$L_{eq}=L_1+L_2$.",
        b: "$L_{eq}=(1/L_1+1/L_2)^{-1}$ only.",
        c: "$L_{eq}=L_1 L_2$.",
      },
      answer: "a",
      why: "Series inductors share current, so inductance adds. Parallel uses the reciprocal sum.",
    },
    {
      id: "p5",
      view: "ind",
      highlight: "eq",
      boardHint: "Right: two paths, same voltage (parallel).",
      prompt: "Two inductors $L_1$ and $L_2$ in parallel have",
      options: {
        a: "$L_{eq}=L_1+L_2$.",
        b: "$L_{eq}=L_1 L_2$.",
        c: "$1/L_{eq}=1/L_1+1/L_2$.",
      },
      answer: "c",
      why: "Parallel: same voltage, currents add, so reciprocals of $L$ add. Series is $L_1+L_2$.",
    },
  ],
};

export const FREEC = {
  steps: [
    {
      id: "why",
      view: "freerc",
      highlight: "all",
      title: "Source-free capacitor",
      boardHint: "No battery. Charged C dumps into R.",
      body: "$C$ and $L$ put derivatives into KCL/KVL, so you get a differential equation. Source-free: the capacitor is already charged, then it dumps into $R$.",
      eq: "$$C\\dfrac{dv}{dt}+\\dfrac{v}{R}=0$$",
      check: {
        prompt: "Source-free RC means",
        options: {
          a: "C is already charged. It dumps into $R$. There is no driving source.",
          b: "A battery is still in the loop, charging C.",
          c: "C is a short circuit.",
        },
        answer: "a",
        why: "No $V_s$. The stored voltage $v(0)$ is the only energy, and it decays through $R$.",
      },
    },
    {
      id: "tau",
      view: "decayc",
      highlight: "curve",
      title: "Exponential and $\\tau$",
      boardHint: "The curve starts at v(0) and falls toward 0. τ = RC.",
      body: "$\\tau$ is the time to decay to $1/e\\approx 36.8\\%$ of the start value.",
      eq: [
        "$$\\dfrac{dv}{dt}=-\\dfrac{1}{RC}v$$",
        "$$v(t)=v(0)\\,e^{-t/\\tau},\\quad \\tau=RC$$",
      ],
      check: {
        prompt: "For source-free RC, $\\tau$ is",
        options: {
          a: "$RC$.",
          b: "$L/R$.",
          c: "$1/RC$.",
        },
        answer: "a",
        why: "RL source-free uses $\\tau=L/R$.",
      },
    },
  ],
  practice: [
    {
      id: "p1",
      view: "freerc",
      highlight: "all",
      boardHint: "No battery. Charged C dumps into R.",
      prompt: "Source-free RC means",
      options: {
        a: "C starts charged and dumps into $R$. No driving source.",
        b: "A DC source stays on forever.",
        c: "C is replaced by a short.",
      },
      answer: "a",
      why: "The only energy is $v(0)$ on C.",
    },
    {
      id: "p2",
      view: "decayc",
      highlight: "curve",
      boardHint: "τ is the time to 1/e of the start value.",
      prompt: "For source-free RC, $\\tau$ is",
      options: {
        a: "$RC$.",
        b: "$L/R$.",
        c: "$R/C$.",
      },
      answer: "a",
      why: "Bigger $R$ or $C$ makes a slower dump.",
    },
    {
      id: "p3",
      view: "decayc",
      highlight: "curve",
      boardHint: "Compare $t$ to $\\tau$ before you punch numbers.",
      prompt: "$v(0)=8\\,\\mathrm{V}$, $\\tau=2\\,\\mathrm{s}$. About how many volts are left at $t=2\\,\\mathrm{s}$?",
      options: {
        a: "$5.06\\,\\mathrm{V}$.",
        b: "$2.94\\,\\mathrm{V}$.",
        c: "$4\\,\\mathrm{V}$.",
      },
      answer: "b",
      why: "$t=\\tau$, so $v=v(0)/e\\approx 2.94\\,\\mathrm{V}$. $5.06\\,\\mathrm{V}$ is $8(1-1/e)$, the charging leftover. $4\\,\\mathrm{V}$ is just $8/2$.",
    },
    {
      id: "p4",
      view: "decayc",
      highlight: "curve",
      boardHint: "The exponential keeps going after $t=\\tau$.",
      prompt: "As $t\\to\\infty$, source-free capacitor voltage goes to",
      options: {
        a: "$0$.",
        b: "$v(0)/e$ and stays there.",
        c: "$V_s$.",
      },
      answer: "a",
      why: "No source is left, so the exponential dies. $v(0)/e$ is only the value at $t=\\tau$, not the end.",
    },
    {
      id: "p5",
      view: "decayc",
      highlight: "curve",
      boardHint: "Bigger C stores more charge, so the dump takes longer.",
      prompt: "$R$ stays the same and $C$ is doubled. $\\tau=RC$ then",
      options: {
        a: "Halves.",
        b: "Stays the same.",
        c: "Doubles.",
      },
      answer: "c",
      why: "$\\tau$ scales with $C$. Halving would be if $C$ were cut in two.",
    },
  ],
};

export const LSOURCE = {
  steps: [
    {
      id: "kvl",
      view: "rlloop",
      highlight: "all",
      title: "Inductor with a source",
      boardHint: "Vs, R, and L stay in the loop. Current cannot jump.",
      body: "For $t>0$, KVL around $V_s$, $R$, and $L$. Initial current cannot jump: $i(0^-)=i(0^+)=I_0$. At $\\infty$, $L$ is a short so $i(\\infty)=V_s/R$.",
      eq: "$$V_s=Ri+L\\dfrac{di}{dt}$$",
      check: {
        prompt: "$I_0=1.5\\,\\mathrm{A}$, $V_s=12\\,\\mathrm{V}$, $R=4\\,\\Omega$. $i(0^+)$ is",
        options: {
          a: "$3\\,\\mathrm{A}$.",
          b: "$1.5\\,\\mathrm{A}$.",
          c: "$0$.",
        },
        answer: "b",
        why: "Current cannot jump, so $i(0^+)=I_0=1.5\\,\\mathrm{A}$. $3\\,\\mathrm{A}$ is $V_s/R$, which is $i(\\infty)$, not the start.",
      },
    },
    {
      id: "sol",
      view: "rlstep",
      highlight: "curve",
      title: "Solution",
      boardHint: "The curve starts at I0 and heads for Vs/R. τ = L/R.",
      eq: [
        "$$\\tau=L/R$$",
        "$$i(t)=\\dfrac{V_s}{R}+\\left(I_0-\\dfrac{V_s}{R}\\right)e^{-t/\\tau}$$",
      ],
      check: {
        prompt: "$V_s=12\\,\\mathrm{V}$, $R=4\\,\\Omega$. $i(\\infty)$ is",
        options: {
          a: "$3\\,\\mathrm{A}$.",
          b: "$0$.",
          c: "$12\\,\\mathrm{A}$.",
        },
        answer: "a",
        why: "$L$ shorts in DC, so $i(\\infty)=V_s/R=3\\,\\mathrm{A}$. $0$ is source-free. $12\\,\\mathrm{A}$ forgot to divide by $R$.",
      },
    },
  ],
  practice: [
    {
      id: "p1",
      view: "rlloop",
      highlight: "all",
      boardHint: "Vs stays in the loop. i cannot jump at t = 0.",
      prompt: "$I_0=0.5\\,\\mathrm{A}$, $V_s=10\\,\\mathrm{V}$, $R=5\\,\\Omega$. $i(0^+)$ is",
      options: {
        a: "$2\\,\\mathrm{A}$.",
        b: "$0.5\\,\\mathrm{A}$.",
        c: "$0$.",
      },
      answer: "b",
      why: "Continuity: $i(0^+)=I_0$. $2\\,\\mathrm{A}$ is $V_s/R=i(\\infty)$.",
    },
    {
      id: "p2",
      view: "rlstep",
      highlight: "curve",
      boardHint: "τ uses L and R, not RC.",
      prompt: "$L=6\\,\\mathrm{mH}$, $R=3\\,\\Omega$. $\\tau$ is",
      options: {
        a: "$18\\,\\mathrm{ms}$.",
        b: "$2\\,\\mathrm{ms}$.",
        c: "$6\\,\\mathrm{ms}$.",
      },
      answer: "b",
      why: "$\\tau=L/R=6\\times 10^{-3}/3=2\\,\\mathrm{ms}$. $18\\,\\mathrm{ms}$ is $L\\times R$ with the milli stuck on. $6\\,\\mathrm{ms}$ just copies $L$.",
    },
    {
      id: "p3",
      view: "rlstep",
      highlight: "curve",
      boardHint: "From rest, current is still climbing at t = τ.",
      prompt: "$I_0=0$, $V_s=8\\,\\mathrm{V}$, $R=4\\,\\Omega$. About how much current is flowing at $t=\\tau$?",
      options: {
        a: "$0.74\\,\\mathrm{A}$.",
        b: "$1.26\\,\\mathrm{A}$.",
        c: "$2\\,\\mathrm{A}$.",
      },
      answer: "b",
      why: "$i(\\infty)=2\\,\\mathrm{A}$. From rest, $i(\\tau)=2(1-1/e)\\approx 1.26\\,\\mathrm{A}$. $0.74\\,\\mathrm{A}$ is $2/e$, the dump leftover. $2\\,\\mathrm{A}$ is the final value, not one $\\tau$ in.",
    },
    {
      id: "p4",
      view: "rlstep",
      highlight: "curve",
      boardHint: "The curve heads for a DC value set by R, not for 0.",
      prompt: "$I_0=1\\,\\mathrm{A}$, $V_s=9\\,\\mathrm{V}$, $R=3\\,\\Omega$. As $t\\to\\infty$, $i$ goes to",
      options: {
        a: "$3\\,\\mathrm{A}$.",
        b: "$1\\,\\mathrm{A}$.",
        c: "$0$.",
      },
      answer: "a",
      why: "$i(\\infty)=V_s/R=3\\,\\mathrm{A}$. It does not stay at $I_0$, and it does not die to $0$ while $V_s$ is still on.",
    },
    {
      id: "p5",
      view: "rlloop",
      highlight: "all",
      boardHint: "From rest, I0 = 0. Forced value is still Vs/R.",
      prompt: "From rest ($I_0=0$), $i(t)$ for $t\\ge 0$ is",
      options: {
        a: "$(V_s/R)(1-e^{-t/\\tau})$.",
        b: "$(V_s/R)e^{-t/\\tau}$.",
        c: "$I_0$ for all $t$.",
      },
      answer: "a",
      why: "Plug $I_0=0$ into $i=V_s/R+(I_0-V_s/R)e^{-t/\\tau}$. The dump formula is source-free.",
    },
  ],
};
