export const SECTION3_PRACTICE = {
  capacitor: [
    {
      id: "s3-c1",
      type: "schematic",
      difficulty: "easy",
      view: "s3-c1",
      prompt:
        "The circuit has sat at DC for a long time. $V_s=15\\,\\mathrm{V}$, $1\\,\\mathrm{k}\\Omega$ in series, $5\\,\\mathrm{k}\\Omega$ in parallel with $C$. What is $v_C$?",
      options: {
        a: "$0$, because an open capacitor cannot hold voltage.",
        b: "$12.5\\,\\mathrm{V}$",
        c: "$15\\,\\mathrm{V}$, skipping the divider.",
        d: "$2.5\\,\\mathrm{V}$, using $1/(1+5)$ on the source.",
      },
      answer: "b",
      why: "Replace $C$ by an open. The remaining divider is $v_C=15\\times 5/(1+5)=12.5\\,\\mathrm{V}$. Open means $i_C=0$, not $v_C=0$.",
    },
    {
      id: "s3-c2",
      type: "schematic",
      difficulty: "medium",
      view: "s3-c2",
      prompt:
        "Long-time DC: $20\\,\\mathrm{V}$, $4\\,\\mathrm{k}\\Omega$, and $C$ in one loop. Which pair is correct?",
      options: {
        a: "$i=5\\,\\mathrm{mA}$ and $v_C=0$.",
        b: "$i=0$ and $v_C=20\\,\\mathrm{V}$.",
        c: "$i=0$ and $v_C=0$.",
        d: "$i=5\\,\\mathrm{mA}$ and $v_C=20\\,\\mathrm{V}$.",
      },
      answer: "b",
      why: "At DC, $C$ is open, so the loop current is $0$ and the resistor drop is $0$. All $20\\,\\mathrm{V}$ sits on $C$.",
    },
    {
      id: "s3-c3",
      type: "schematic",
      difficulty: "medium",
      view: "s3-c3",
      prompt:
        "Long-time DC: $9\\,\\mathrm{V}$, $3\\,\\mathrm{k}\\Omega$ in series, $6\\,\\mathrm{k}\\Omega$ in parallel with $C$. What is the current in the $3\\,\\mathrm{k}\\Omega$?",
      options: {
        a: "$0$, because $C$ is open.",
        b: "$1\\,\\mathrm{mA}$",
        c: "$1.5\\,\\mathrm{mA}$, using only $9/6\\,\\mathrm{k}\\Omega$.",
        d: "$3\\,\\mathrm{mA}$, using only $9/3\\,\\mathrm{k}\\Omega$.",
      },
      answer: "b",
      why: "$C$ is open, so the $6\\,\\mathrm{k}\\Omega$ still carries the divider current $9/(3+6)\\,\\mathrm{k}\\Omega=1\\,\\mathrm{mA}$. That same current is in the $3\\,\\mathrm{k}\\Omega$. $i_C$ is $0$, not the resistor current.",
    },
    {
      id: "s3-c4",
      type: "schematic",
      difficulty: "harder",
      view: "s3-c4",
      prompt:
        "Long-time DC: $24\\,\\mathrm{V}$, $8\\,\\mathrm{k}\\Omega$ in series, $24\\,\\mathrm{k}\\Omega$ in parallel with $C=5\\,\\mu\\mathrm{F}$. Energy stored in $C$?",
      options: {
        a: "$810\\,\\mu\\mathrm{J}$",
        b: "$1.44\\,\\mathrm{mJ}$, using $v=24\\,\\mathrm{V}$.",
        c: "$90\\,\\mu\\mathrm{J}$, using $\\tfrac12 C v$ instead of $v^2$.",
        d: "$0$, because $i_C=0$.",
      },
      answer: "a",
      why: "$v_C=24\\times 24/(8+24)=18\\,\\mathrm{V}$. Then $w=\\tfrac12 C v_C^2=\\tfrac12(5\\times 10^{-6})(18)^2=810\\,\\mu\\mathrm{J}$. Zero current does not mean zero stored energy.",
    },
    {
      id: "s3-c5",
      type: "schematic",
      difficulty: "medium",
      view: "s3-c5",
      prompt:
        "Long-time DC: $10\\,\\mathrm{V}$, $2\\,\\mathrm{k}\\Omega$ in series, $8\\,\\mathrm{k}\\Omega$ in parallel with $C$. What is $i_C$?",
      options: {
        a: "$1\\,\\mathrm{mA}$, the divider current.",
        b: "$1.25\\,\\mathrm{mA}$, using $10/8\\,\\mathrm{k}\\Omega$.",
        c: "$0$",
        d: "$5\\,\\mathrm{mA}$, using $10/2\\,\\mathrm{k}\\Omega$.",
      },
      answer: "c",
      why: "At DC, $i=C\\,dv/dt=0$. The $1\\,\\mathrm{mA}$ divider current is in the resistors, not through $C$.",
    },
    {
      id: "s3-c6",
      type: "schematic",
      difficulty: "easy",
      view: "s3-c6",
      prompt:
        "The circuit has sat at DC for a long time. What is the voltage across the $3\\,\\mathrm{k}\\Omega$ resistor?",
      options: {
        a: "$0\\,\\mathrm{V}$, because the capacitor is open.",
        b: "$12\\,\\mathrm{V}$, using the capacitor voltage instead.",
        c: "$18\\,\\mathrm{V}$, putting the full source across the $3\\,\\mathrm{k}\\Omega$.",
        d: "$6\\,\\mathrm{V}$",
      },
      answer: "d",
      why: "$C$ is open at DC. The resistor current is $18/(3+6)\\,\\mathrm{k}\\Omega=2\\,\\mathrm{mA}$. The $3\\,\\mathrm{k}\\Omega$ drop is $2\\,\\mathrm{mA}\\times 3\\,\\mathrm{k}\\Omega=6\\,\\mathrm{V}$.",
    },
    {
      id: "s3-c7",
      type: "schematic",
      difficulty: "medium",
      view: "s3-c7",
      prompt: "What is $v_C$ after a long time?",
      options: {
        a: "$3\\,\\mathrm{V}$",
        b: "$7\\,\\mathrm{V}$",
        c: "$18\\,\\mathrm{V}$",
        d: "$21\\,\\mathrm{V}$",
      },
      answer: "c",
      why: "$C$ is open. The resistor path is $2+4+8=14\\,\\mathrm{k}\\Omega$. Current is $21/14\\,\\mathrm{k}\\Omega=1.5\\,\\mathrm{mA}$. From $A$ to ground: $1.5\\,\\mathrm{mA}\\times(4+8)\\,\\mathrm{k}\\Omega=18\\,\\mathrm{V}$.",
    },
    {
      id: "s3-c8",
      type: "schematic",
      difficulty: "medium",
      view: "s3-c8",
      prompt: "Long-time DC. Which pair is correct for the source current and capacitor current?",
      options: {
        a: "$I_s=3\\,\\mathrm{mA}$ and $i_C=3\\,\\mathrm{mA}$",
        b: "$I_s=2\\,\\mathrm{mA}$ and $i_C=0$",
        c: "$I_s=0$ and $i_C=0$",
        d: "$I_s=6\\,\\mathrm{mA}$ and $i_C=0$",
      },
      answer: "b",
      why: "At DC the capacitor branch is open, but the $2\\,\\mathrm{k}\\Omega$ and $4\\,\\mathrm{k}\\Omega$ still conduct. $I_s=12/(2+4)\\,\\mathrm{k}\\Omega=2\\,\\mathrm{mA}$ and $i_C=0$.",
    },
    {
      id: "s3-c9",
      type: "schematic",
      difficulty: "harder",
      view: "s3-c9",
      prompt: "Long-time DC. How much energy is stored in the capacitor?",
      options: {
        a: "$0\\,\\mathrm{J}$, because $i_C=0$.",
        b: "$3.6\\,\\mathrm{mJ}$, using the full $30\\,\\mathrm{V}$.",
        c: "$0.8\\,\\mathrm{mJ}$",
        d: "$1.6\\,\\mathrm{mJ}$",
      },
      answer: "d",
      why: "$C$ is open at DC. $v_C=30\\times 10/(5+10)=20\\,\\mathrm{V}$. $w_C=\\tfrac12 C v_C^2=\\tfrac12(8\\times 10^{-6})(20)^2=1.6\\,\\mathrm{mJ}$.",
    },
    {
      id: "s3-c10",
      type: "schematic",
      difficulty: "harder",
      view: "s3-c10",
      prompt: "Long-time DC. What current flows through EACH $6\\,\\mathrm{k}\\Omega$ resistor?",
      options: {
        a: "$1.5\\,\\mathrm{mA}$",
        b: "$3\\,\\mathrm{mA}$",
        c: "$0.75\\,\\mathrm{mA}$",
        d: "$0$, because the capacitor is open.",
      },
      answer: "a",
      why: "$C$ is open. The two $6\\,\\mathrm{k}\\Omega$ resistors give $3\\,\\mathrm{k}\\Omega$ from $A$ to ground. The divider is $3\\,\\mathrm{k}\\Omega$ with $3\\,\\mathrm{k}\\Omega$, so $v_A=9\\,\\mathrm{V}$. Each $6\\,\\mathrm{k}\\Omega$ branch carries $9/6\\,\\mathrm{k}\\Omega=1.5\\,\\mathrm{mA}$.",
    },
    {
      id: "s3-c11",
      type: "schematic",
      difficulty: "harder",
      view: "s3-c11",
      prompt: "Long-time DC. What is $v_C$?",
      options: {
        a: "$6\\,\\mathrm{V}$",
        b: "$9\\,\\mathrm{V}$",
        c: "$10\\,\\mathrm{V}$",
        d: "$12\\,\\mathrm{V}$",
      },
      answer: "c",
      why: "$C$ is open at DC. KCL at $A$: $(v_A-12)/2\\,\\mathrm{k}\\Omega+(v_A-6)/4\\,\\mathrm{k}\\Omega=0$. Multiply by $4\\,\\mathrm{k}\\Omega$: $2(v_A-12)+(v_A-6)=0$, so $3v_A=30$ and $v_C=v_A=10\\,\\mathrm{V}$.",
    },
  ],
  inductor: [
    {
      id: "s3-l1",
      type: "schematic",
      difficulty: "easy",
      view: "s3-l1",
      prompt:
        "Long-time DC: $18\\,\\mathrm{V}$, $2\\,\\Omega$ in series, $4\\,\\Omega$ in parallel with $L$. What is $i_L$?",
      options: {
        a: "$0$, treating $L$ as an open circuit.",
        b: "$4.5\\,\\mathrm{A}$, sending all the source current through the $4\\,\\Omega$.",
        c: "$9\\,\\mathrm{A}$",
        d: "$3\\,\\mathrm{A}$, putting $2\\,\\Omega$ and $4\\,\\Omega$ in series.",
      },
      answer: "c",
      why: "At DC, $L$ is a short, so it shorts the $4\\,\\Omega$. Then $i_L=18/2=9\\,\\mathrm{A}$.",
    },
    {
      id: "s3-l2",
      type: "schematic",
      difficulty: "medium",
      view: "s3-l2",
      prompt:
        "Long-time DC: $10\\,\\mathrm{V}$, $5\\,\\Omega$, and $L$ in one loop. Which pair is correct?",
      options: {
        a: "$v_L=10\\,\\mathrm{V}$ and $i_L=0$, treating $L$ as open.",
        b: "$v_L=0$ and $i_L=2\\,\\mathrm{A}$.",
        c: "$v_L=0$ and $i_L=0$.",
        d: "$v_L=10\\,\\mathrm{V}$ and $i_L=2\\,\\mathrm{A}$.",
      },
      answer: "b",
      why: "$v=L\\,di/dt=0$ at DC, so $L$ is a short. Then $i_L=10/5=2\\,\\mathrm{A}$.",
    },
    {
      id: "s3-l3",
      type: "schematic",
      difficulty: "medium",
      view: "s3-l3",
      prompt:
        "Long-time DC: $24\\,\\mathrm{V}$, $6\\,\\Omega$ in series, $12\\,\\Omega$ in parallel with $L$. What is the current in the $12\\,\\Omega$?",
      options: {
        a: "$2\\,\\mathrm{A}$, using $24/12$.",
        b: "$4\\,\\mathrm{A}$, using $24/6$.",
        c: "$1.33\\,\\mathrm{A}$, putting $6\\,\\Omega$ and $12\\,\\Omega$ in series.",
        d: "$0$",
      },
      answer: "d",
      why: "$L$ shorts the $12\\,\\Omega$, so that branch is bypassed. All $24/6=4\\,\\mathrm{A}$ goes through $L$.",
    },
    {
      id: "s3-l4",
      type: "schematic",
      difficulty: "harder",
      view: "s3-l4",
      prompt:
        "Long-time DC: $12\\,\\mathrm{V}$, $4\\,\\Omega$ in series with $L=8\\,\\mathrm{mH}$. Energy stored in $L$?",
      options: {
        a: "$36\\,\\mathrm{mJ}$",
        b: "$48\\,\\mathrm{mJ}$, using $\\tfrac12 L i$ instead of $i^2$.",
        c: "$0$, because $v_L=0$.",
        d: "$144\\,\\mathrm{mJ}$, using the source voltage in $\\tfrac12 L v^2$.",
      },
      answer: "a",
      why: "$L$ is a short, so $i_L=12/4=3\\,\\mathrm{A}$. Then $w=\\tfrac12 L i_L^2=\\tfrac12(8\\times 10^{-3})(3)^2=36\\,\\mathrm{mJ}$.",
    },
    {
      id: "s3-l5",
      type: "schematic",
      difficulty: "medium",
      view: "s3-l5",
      prompt:
        "Long-time DC: $15\\,\\mathrm{V}$, $5\\,\\Omega$ in series, $10\\,\\Omega$ in parallel with $L$. What is $i_L$?",
      options: {
        a: "$1\\,\\mathrm{A}$, putting $5\\,\\Omega$ and $10\\,\\Omega$ in series.",
        b: "$1.5\\,\\mathrm{A}$, using only the $10\\,\\Omega$.",
        c: "$3\\,\\mathrm{A}$",
        d: "$0$, treating $L$ as an open circuit.",
      },
      answer: "c",
      why: "$L$ shorts the $10\\,\\Omega$, so $i_L=15/5=3\\,\\mathrm{A}$.",
    },
    {
      id: "s3-l6",
      type: "schematic",
      difficulty: "easy",
      view: "s3-l6",
      prompt: "Long-time DC. What is the voltage across the $8\\,\\Omega$ resistor?",
      options: {
        a: "$0\\,\\mathrm{V}$",
        b: "$10\\,\\mathrm{V}$",
        c: "$20\\,\\mathrm{V}$",
        d: "$40\\,\\mathrm{V}$",
      },
      answer: "a",
      why: "At long-time DC the ideal inductor is a short from $N$ to ground. The $8\\,\\Omega$ is in parallel with that short, so its voltage is $0$.",
    },
    {
      id: "s3-l7",
      type: "schematic",
      difficulty: "medium",
      view: "s3-l7",
      prompt: "Long-time DC. What is the source current?",
      options: {
        a: "$2\\,\\mathrm{A}$",
        b: "$3\\,\\mathrm{A}$",
        c: "$6\\,\\mathrm{A}$",
        d: "$10\\,\\mathrm{A}$",
      },
      answer: "c",
      why: "$L$ shorts the $10\\,\\Omega$ branch. The source sees $3\\,\\Omega+2\\,\\Omega=5\\,\\Omega$, so $I_s=30/5=6\\,\\mathrm{A}$.",
    },
    {
      id: "s3-l8",
      type: "schematic",
      difficulty: "medium",
      view: "s3-l8",
      prompt: "Long-time DC. How much energy is stored in the inductor?",
      options: {
        a: "$0$, because $v_L=0$.",
        b: "$40\\,\\mathrm{mJ}$",
        c: "$80\\,\\mathrm{mJ}$",
        d: "$160\\,\\mathrm{mJ}$",
      },
      answer: "d",
      why: "$L$ shorts the $12\\,\\Omega$ branch. $i_L=24/6=4\\,\\mathrm{A}$. $w_L=\\tfrac12 L i_L^2=\\tfrac12(20\\times 10^{-3})(4)^2=0.16\\,\\mathrm{J}=160\\,\\mathrm{mJ}$.",
    },
    {
      id: "s3-l9",
      type: "schematic",
      difficulty: "harder",
      view: "s3-l9",
      prompt: "Long-time DC. The arrow $i_L$ is from $N$ through $L$ to ground. What is $i_L$?",
      options: {
        a: "$5\\,\\mathrm{A}$",
        b: "$7\\,\\mathrm{A}$",
        c: "$6\\,\\mathrm{A}$",
        d: "$1\\,\\mathrm{A}$",
      },
      answer: "b",
      why: "$L$ is a short, so $N$ is at $0\\,\\mathrm{V}$. The $18\\,\\mathrm{V}$ branch contributes $18/3=6\\,\\mathrm{A}$ into $N$ and the $6\\,\\mathrm{V}$ branch contributes $6/6=1\\,\\mathrm{A}$. KCL gives $i_L=7\\,\\mathrm{A}$.",
    },
    {
      id: "s3-l10",
      type: "schematic",
      difficulty: "harder",
      view: "s3-l10",
      prompt: "Long-time DC. What is $i_L$?",
      options: {
        a: "$2\\,\\mathrm{A}$",
        b: "$6\\,\\mathrm{A}$",
        c: "$8\\,\\mathrm{A}$",
        d: "$24\\,\\mathrm{A}$",
      },
      answer: "c",
      why: "$L$ is a short. The source sees $4\\,\\Omega\\parallel 12\\,\\Omega=3\\,\\Omega$. Therefore $i_L$ is the total source current, $24/3=8\\,\\mathrm{A}$.",
    },
    {
      id: "s3-l11",
      type: "schematic",
      difficulty: "harder",
      view: "s3-l11",
      prompt: "Long-time DC. What is $i_L$?",
      options: {
        a: "$2\\,\\mathrm{A}$",
        b: "$\\tfrac{8}{3}\\,\\mathrm{A}$",
        c: "$4\\,\\mathrm{A}$",
        d: "$6\\,\\mathrm{A}$",
      },
      answer: "a",
      why: "At DC, $L$ is a short, so the inductor branch is $4\\,\\Omega$. The load at $N$ is $12\\,\\Omega\\parallel 4\\,\\Omega=3\\,\\Omega$. Total current is $24/(6+3)=8/3\\,\\mathrm{A}$, so $v_N=(8/3)\\times 3=8\\,\\mathrm{V}$. The inductor branch current is $8/4=2\\,\\mathrm{A}$.",
    },
  ],
  freec: [
    {
      id: "s3-f1",
      type: "schematic",
      difficulty: "easy",
      view: "s3-f1",
      prompt:
        "After $t=0$ the source is gone and $C=20\\,\\mu\\mathrm{F}$ sees $4\\,\\mathrm{k}\\Omega$ in parallel with $12\\,\\mathrm{k}\\Omega$. What is $\\tau$?",
      options: {
        a: "$80\\,\\mathrm{ms}$, using only $4\\,\\mathrm{k}\\Omega$.",
        b: "$240\\,\\mathrm{ms}$, using only $12\\,\\mathrm{k}\\Omega$.",
        c: "$60\\,\\mathrm{ms}$",
        d: "$320\\,\\mathrm{ms}$, adding $4\\,\\mathrm{k}\\Omega$ and $12\\,\\mathrm{k}\\Omega$.",
      },
      answer: "c",
      why: "$R_{Th}=4\\,\\mathrm{k}\\Omega\\parallel 12\\,\\mathrm{k}\\Omega=3\\,\\mathrm{k}\\Omega$. Then $\\tau=R_{Th}C=3\\times 10^3\\times 20\\times 10^{-6}=60\\,\\mathrm{ms}$.",
    },
    {
      id: "s3-f2",
      type: "schematic",
      difficulty: "medium",
      view: "s3-f2",
      prompt:
        "For $t<0$ the $16\\,\\mathrm{V}$ source feeds $1\\,\\mathrm{k}\\Omega$ into node $A$, with $3\\,\\mathrm{k}\\Omega$ and $C$ in parallel from $A$ to ground. At $t=0$ the source is replaced by a short, so both resistors remain across $C$. What is $v_C(0^+)$?",
      options: {
        a: "$12\\,\\mathrm{V}$",
        b: "$0$, because the dump starts at once.",
        c: "$16\\,\\mathrm{V}$",
        d: "$4\\,\\mathrm{V}$, using $1/(1+3)$.",
      },
      answer: "a",
      why: "At DC, $C$ is open, so $v_C(0^-)=16\\times 3/(1+3)=12\\,\\mathrm{V}$. Capacitor voltage cannot jump, so $v_C(0^+)=12\\,\\mathrm{V}$. After $t=0$, $R_{Th}=1\\,\\mathrm{k}\\Omega\\parallel 3\\,\\mathrm{k}\\Omega=750\\,\\Omega$, but that is not needed for $v_C(0^+)$.",
    },
    {
      id: "s3-f3",
      type: "schematic",
      difficulty: "harder",
      view: "s3-f3",
      prompt:
        "For $t<0$, $24\\,\\mathrm{V}$ feeds $2\\,\\mathrm{k}\\Omega$ into node $A$, with $6\\,\\mathrm{k}\\Omega$ and $C=4\\,\\mu\\mathrm{F}$ in parallel from $A$ to ground. At $t=0$ the source is replaced by a short, so both resistors remain across $C$. Which statement is complete and correct?",
      options: {
        a: "$v_C(0^+)=18\\,\\mathrm{V}$, $\\tau=6\\,\\mathrm{ms}$, and $v_C(\\infty)=0$.",
        b: "$v_C(0^+)=0$, because the dump starts at once.",
        c: "$v_C(0^+)=24\\,\\mathrm{V}$ and $\\tau=16\\,\\mathrm{ms}$, adding the two resistors.",
        d: "$v_C(0^+)=18\\,\\mathrm{V}$ and $v_C(\\infty)=18\\,\\mathrm{V}$.",
      },
      answer: "a",
      why: "Divider at DC: $v_C(0^-)=24\\times 6/(2+6)=18\\,\\mathrm{V}=v_C(0^+)$. After the source is replaced by a short, $R_{Th}=2\\,\\mathrm{k}\\Omega\\parallel 6\\,\\mathrm{k}\\Omega=1.5\\,\\mathrm{k}\\Omega$, so $\\tau=1.5\\times 10^3\\times 4\\times 10^{-6}=6\\,\\mathrm{ms}$. $v_C(\\infty)=0$.",
    },
    {
      id: "s3-f4",
      type: "schematic",
      difficulty: "medium",
      view: "s3-f4",
      prompt:
        "$C=8\\,\\mu\\mathrm{F}$ is already charged to $20\\,\\mathrm{V}$. At $t=0$ it dumps into $5\\,\\mathrm{k}\\Omega$ only. What is $v_C(t)$ for $t\\ge 0$?",
      options: {
        a: "$20e^{-t/(40\\,\\mathrm{ms})}\\,\\mathrm{V}$",
        b: "$20\\bigl(1-e^{-t/(40\\,\\mathrm{ms})}\\bigr)\\,\\mathrm{V}$",
        c: "$20e^{-t/(5\\,\\mathrm{ms})}\\,\\mathrm{V}$, mixing $R$ in k$\\Omega$ with $C$ in $\\mu\\mathrm{F}$ incorrectly.",
        d: "$0$ for all $t>0$.",
      },
      answer: "a",
      why: "$\\tau=RC=5\\times 10^3\\times 8\\times 10^{-6}=40\\,\\mathrm{ms}$. Source-free: $v_C(t)=v_C(0)e^{-t/\\tau}$. The $(1-e^{-t/\\tau})$ shape is a step toward a nonzero final value.",
    },
    {
      id: "s3-f5",
      type: "schematic",
      difficulty: "harder",
      view: "s3-f5",
      prompt:
        "For $t<0$, $30\\,\\mathrm{V}$ feeds $3\\,\\mathrm{k}\\Omega$ into node $A$, with $9\\,\\mathrm{k}\\Omega$ and $C=10\\,\\mu\\mathrm{F}$ in parallel from $A$ to ground. At $t=0$ the source is replaced by a short, so both resistors remain across $C$. What is $\\tau$?",
      options: {
        a: "$30\\,\\mathrm{ms}$, using only $3\\,\\mathrm{k}\\Omega$.",
        b: "$90\\,\\mathrm{ms}$, using only $9\\,\\mathrm{k}\\Omega$.",
        c: "$22.5\\,\\mathrm{ms}$",
        d: "$120\\,\\mathrm{ms}$, adding $3\\,\\mathrm{k}\\Omega$ and $9\\,\\mathrm{k}\\Omega$.",
      },
      answer: "c",
      why: "$R_{Th}=3\\,\\mathrm{k}\\Omega\\parallel 9\\,\\mathrm{k}\\Omega=2.25\\,\\mathrm{k}\\Omega$. Then $\\tau=2.25\\times 10^3\\times 10\\times 10^{-6}=22.5\\,\\mathrm{ms}$. Continuity still gives $v_C(0^+)=30\\times 9/12=22.5\\,\\mathrm{V}$, but that is not $\\tau$.",
    },
    {
      id: "s3-f6",
      type: "schematic",
      difficulty: "harder",
      view: "s3-f6",
      prompt:
        "For $t<0$, $10\\,\\mathrm{V}$ feeds $4\\,\\mathrm{k}\\Omega$ into node $A$, with $4\\,\\mathrm{k}\\Omega$ and $C=2\\,\\mu\\mathrm{F}$ in parallel from $A$ to ground. At $t=0$ the source branch opens, so the series $4\\,\\mathrm{k}\\Omega$ leaves the circuit. $C$ dumps only through the $4\\,\\mathrm{k}\\Omega$ already across it. What is $v_C(t)$ for $t\\ge 0$?",
      options: {
        a: "$5e^{-t/(8\\,\\mathrm{ms})}\\,\\mathrm{V}$",
        b: "$10e^{-t/(8\\,\\mathrm{ms})}\\,\\mathrm{V}$",
        c: "$5e^{-t/(16\\,\\mathrm{ms})}\\,\\mathrm{V}$, keeping both resistors in $R_{Th}$.",
        d: "$v_C(0^+)=0$.",
      },
      answer: "a",
      why: "Before $t=0$, $v_C(0^-)=10\\times 4/(4+4)=5\\,\\mathrm{V}=v_C(0^+)$. After the source branch opens, $R_{Th}=4\\,\\mathrm{k}\\Omega$, so $\\tau=4\\times 10^3\\times 2\\times 10^{-6}=8\\,\\mathrm{ms}$. Then $v_C(t)=5e^{-t/(8\\,\\mathrm{ms})}\\,\\mathrm{V}$.",
    },
    {
      id: "s3-f7",
      type: "schematic",
      difficulty: "medium",
      view: "s3-f7",
      prompt: "What is $v_C(t)$ for $t\\ge 0$?",
      options: {
        a: "$18e^{-t/(24\\,\\mathrm{ms})}\\,\\mathrm{V}$",
        b: "$12e^{-t/(24\\,\\mathrm{ms})}\\,\\mathrm{V}$",
        c: "$12\\bigl(1-e^{-t/(24\\,\\mathrm{ms})}\\bigr)\\,\\mathrm{V}$",
        d: "$12e^{-t/(12\\,\\mathrm{ms})}\\,\\mathrm{V}$",
      },
      answer: "b",
      why: "$v_C(0^-)=18\\times 4/(2+4)=12\\,\\mathrm{V}=v_C(0^+)$. After the source branch opens, $R_{Th}=4\\,\\mathrm{k}\\Omega$. $\\tau=4\\times 10^3\\times 6\\times 10^{-6}=24\\,\\mathrm{ms}$. Source-free: $12e^{-t/(24\\,\\mathrm{ms})}\\,\\mathrm{V}$.",
    },
    {
      id: "s3-f8",
      type: "schematic",
      difficulty: "harder",
      view: "s3-f8",
      prompt: "Approximately what is $v_C$ at $t=30\\,\\mathrm{ms}$?",
      options: {
        a: "$15.0\\,\\mathrm{V}$",
        b: "$7.5\\,\\mathrm{V}$",
        c: "$5.52\\,\\mathrm{V}$",
        d: "$2.03\\,\\mathrm{V}$",
      },
      answer: "d",
      why: "$v_C(0^+)=20\\times 15/(5+15)=15\\,\\mathrm{V}$. $R_{Th}=5\\,\\mathrm{k}\\Omega\\parallel 15\\,\\mathrm{k}\\Omega=3.75\\,\\mathrm{k}\\Omega$. $\\tau=3.75\\times 10^3\\times 4\\times 10^{-6}=15\\,\\mathrm{ms}$. At $30\\,\\mathrm{ms}=2\\tau$, $v_C=15e^{-2}=2.03\\,\\mathrm{V}$.",
    },
    {
      id: "s3-f9",
      type: "schematic",
      difficulty: "harder",
      view: "s3-f9",
      prompt:
        "Source-free $C=10\\,\\mu\\mathrm{F}$ is in parallel with $6\\,\\mathrm{k}\\Omega$ and an unknown resistor $R_x$. The measured time constant is $40\\,\\mathrm{ms}$. What is $R_x$?",
      options: {
        a: "$4\\,\\mathrm{k}\\Omega$",
        b: "$6\\,\\mathrm{k}\\Omega$",
        c: "$12\\,\\mathrm{k}\\Omega$",
        d: "$24\\,\\mathrm{k}\\Omega$",
      },
      answer: "c",
      why: "$R_{Th}=\\tau/C=(40\\times 10^{-3})/(10\\times 10^{-6})=4\\,\\mathrm{k}\\Omega$. Need $6\\,\\mathrm{k}\\Omega\\parallel R_x=4\\,\\mathrm{k}\\Omega$. $1/R_x=1/4\\,\\mathrm{k}\\Omega-1/6\\,\\mathrm{k}\\Omega=1/12\\,\\mathrm{k}\\Omega$, so $R_x=12\\,\\mathrm{k}\\Omega$.",
    },
    {
      id: "s3-f10",
      type: "schematic",
      difficulty: "medium",
      view: "s3-f10",
      prompt:
        "Two source-free capacitor circuits start at the same initial voltage. Which statement is correct?",
      options: {
        a: "They decay at the same rate because both have $\\tau=16\\,\\mathrm{ms}$.",
        b: "Circuit A decays faster because its resistance is smaller.",
        c: "Circuit B decays faster because its capacitance is smaller.",
        d: "Circuit A has twice the time constant of Circuit B.",
      },
      answer: "a",
      why: "$\\tau_A=2\\times 10^3\\times 8\\times 10^{-6}=16\\,\\mathrm{ms}$. $\\tau_B=4\\times 10^3\\times 4\\times 10^{-6}=16\\,\\mathrm{ms}$. Equal $\\tau$ means the same normalized decay rate.",
    },
    {
      id: "s3-f11",
      type: "schematic",
      difficulty: "harder",
      view: "s3-f11",
      prompt: "Which expression correctly describes $v_C(t)$ for $t\\ge 0$?",
      options: {
        a: "$12e^{-t/(11.25\\,\\mathrm{ms})}\\,\\mathrm{V}$",
        b: "$9e^{-t/(11.25\\,\\mathrm{ms})}\\,\\mathrm{V}$",
        c: "$9e^{-t/(45\\,\\mathrm{ms})}\\,\\mathrm{V}$",
        d: "$9\\bigl(1-e^{-t/(11.25\\,\\mathrm{ms})}\\bigr)\\,\\mathrm{V}$",
      },
      answer: "b",
      why: "$v_C(0^+)=12\\times 9/(3+9)=9\\,\\mathrm{V}$. $R_{Th}=3\\,\\mathrm{k}\\Omega\\parallel 9\\,\\mathrm{k}\\Omega=2.25\\,\\mathrm{k}\\Omega$. $\\tau=2.25\\times 10^3\\times 5\\times 10^{-6}=11.25\\,\\mathrm{ms}$. Therefore $v_C(t)=9e^{-t/(11.25\\,\\mathrm{ms})}\\,\\mathrm{V}$.",
    },
    {
      id: "s3-f12",
      type: "schematic",
      difficulty: "harder",
      view: "s3-f12",
      prompt:
        "$C=10\\,\\mu\\mathrm{F}$ is initially charged to $10\\,\\mathrm{V}$ and discharges through $2\\,\\mathrm{k}\\Omega$. How much energy remains in the capacitor after one time constant?",
      options: {
        a: "$500\\,\\mu\\mathrm{J}$",
        b: "$184\\,\\mu\\mathrm{J}$, assuming energy falls by $e^{-1}$.",
        c: "$0$",
        d: "About $67.7\\,\\mu\\mathrm{J}$",
      },
      answer: "d",
      why: "$\\tau=2\\,\\mathrm{k}\\Omega\\times 10\\,\\mu\\mathrm{F}=20\\,\\mathrm{ms}$. Initial energy is $\\tfrac12 C V_0^2=500\\,\\mu\\mathrm{J}$. After one $\\tau$, voltage is $V_0/e$, so energy is $W_0/e^2=500/e^2=67.7\\,\\mu\\mathrm{J}$.",
    },
  ],
  lsource: [
    {
      id: "s3-s1",
      type: "schematic",
      difficulty: "easy",
      view: "s3-s1",
      prompt:
        "The source stays connected. After a long time, $V_s=20\\,\\mathrm{V}$, $5\\,\\Omega$ in series, $15\\,\\Omega$ in parallel with $L$. What is $i_L$?",
      options: {
        a: "$0$, treating $L$ as an open circuit.",
        b: "$\\tfrac{4}{3}\\,\\mathrm{A}$, using only the $15\\,\\Omega$.",
        c: "$1\\,\\mathrm{A}$, putting $5\\,\\Omega$ and $15\\,\\Omega$ in series.",
        d: "$4\\,\\mathrm{A}$",
      },
      answer: "d",
      why: "At DC, $L$ shorts the $15\\,\\Omega$. Then $i_L(\\infty)=20/5=4\\,\\mathrm{A}$. That is the forced value while $V_s$ is still on.",
    },
    {
      id: "s3-s2",
      type: "schematic",
      difficulty: "medium",
      view: "s3-s2",
      prompt:
        "For $t<0$ a closed switch shorts the extra $9\\,\\Omega$, leaving $36\\,\\mathrm{V}$, $3\\,\\Omega$, and $L$. At $t=0$ the short opens, so $3\\,\\Omega$ and $9\\,\\Omega$ are both in series with $L$. Which statement is correct?",
      options: {
        a: "$i_L(0^-)=12\\,\\mathrm{A}$, $i_L(0^+)=0$, $i_L(\\infty)=3\\,\\mathrm{A}$.",
        b: "$i_L(0^-)=12\\,\\mathrm{A}$, $i_L(0^+)=12\\,\\mathrm{A}$, $i_L(\\infty)=3\\,\\mathrm{A}$.",
        c: "$i_L$ stays $12\\,\\mathrm{A}$ for all $t$.",
        d: "$i_L(0^+)=4\\,\\mathrm{A}$, putting $3\\,\\Omega$ and $9\\,\\Omega$ in series before $t=0$.",
      },
      answer: "b",
      why: "Before $t=0$, $L$ shorts and $i_L(0^-)=36/3=12\\,\\mathrm{A}$. Current cannot jump, so $i_L(0^+)=12\\,\\mathrm{A}$. After the extra $9\\,\\Omega$ is in, $i_L(\\infty)=36/(3+9)=3\\,\\mathrm{A}$.",
    },
    {
      id: "s3-s3",
      type: "schematic",
      difficulty: "harder",
      view: "s3-s3",
      prompt:
        "For $t<0$, $30\\,\\mathrm{V}$ feeds $4\\,\\Omega$ in series and $12\\,\\Omega$ in parallel with $L$. At $t=0$ the source is removed, leaving $L$ with the $12\\,\\Omega$. Which statement is complete and correct?",
      options: {
        a: "$i_L$ jumps to $0$ at $t=0^+$ because the source is gone.",
        b: "$i_L(0^+)=7.5\\,\\mathrm{A}$, $i_L(\\infty)=0$, and $i_L(t)$ decays with $\\tau=L/12\\,\\Omega$.",
        c: "$i_L(0^+)=7.5\\,\\mathrm{A}$ and $i_L(\\infty)=2.5\\,\\mathrm{A}$, keeping $30/12$.",
        d: "$i_L(0^+)=2.5\\,\\mathrm{A}$, treating the $4\\,\\Omega$ and $12\\,\\Omega$ as series before $t=0$.",
      },
      answer: "b",
      why: "Before $t=0$, $L$ shorts the $12\\,\\Omega$, so $i_L(0^-)=30/4=7.5\\,\\mathrm{A}=i_L(0^+)$. After the source is gone, $i_L(\\infty)=0$ and $R_{Th}=12\\,\\Omega$, so $\\tau=L/12\\,\\Omega$.",
    },
    {
      id: "s3-s4",
      type: "schematic",
      difficulty: "easy",
      view: "s3-s4",
      prompt:
        "The source stays on. After a long time, $V_s=16\\,\\mathrm{V}$ and $8\\,\\Omega$ in series with $L$. What is $i_L(\\infty)$?",
      options: {
        a: "$0$, treating $L$ as an open circuit.",
        b: "$2\\,\\mathrm{A}$",
        c: "$16\\,\\mathrm{A}$, skipping $R$.",
        d: "Infinite, because $L$ is a short.",
      },
      answer: "b",
      why: "$L$ is a short at DC, so $i_L(\\infty)=16/8=2\\,\\mathrm{A}$. Then $\\tau=L/8\\,\\Omega$ for the approach to that forced value.",
    },
    {
      id: "s3-s5",
      type: "schematic",
      difficulty: "harder",
      view: "s3-s5",
      prompt:
        "For $t<0$ a closed switch shorts the extra $10\\,\\Omega$, leaving $15\\,\\mathrm{V}$, $5\\,\\Omega$, and $L$. At $t=0$ the short opens. What is $i_L(t)$ for $t\\ge 0$?",
      options: {
        a: "$3e^{-t/\\tau}\\,\\mathrm{A}$, forgetting the new forced value.",
        b: "$1+(3-1)e^{-t/\\tau}\\,\\mathrm{A}$ with $\\tau=L/15\\,\\Omega$.",
        c: "$1\\,\\mathrm{A}$ immediately at $t=0^+$.",
        d: "$3\\,\\mathrm{A}$ for all $t$, because current cannot change.",
      },
      answer: "b",
      why: "$i_L(0^-)=15/5=3\\,\\mathrm{A}=i_L(0^+)$. After the extra $10\\,\\Omega$ is in, $i_L(\\infty)=15/15=1\\,\\mathrm{A}$ and $R_{Th}=15\\,\\Omega$, so $\\tau=L/15\\,\\Omega$ and $i_L(t)=1+(3-1)e^{-t/\\tau}\\,\\mathrm{A}$.",
    },
    {
      id: "s3-s6",
      type: "schematic",
      difficulty: "harder",
      view: "s3-s6",
      prompt:
        "For $t<0$, $48\\,\\mathrm{V}$ feeds $6\\,\\Omega$ in series and $18\\,\\Omega$ in parallel with $L$. At $t=0$ the source is removed, leaving $L$ with the $18\\,\\Omega$. Which statement is complete and correct?",
      options: {
        a: "$i_L(0^+)=8\\,\\mathrm{A}$, $i_L(\\infty)=0$, and $\\tau=L/18\\,\\Omega$.",
        b: "$i_L(0^+)=8\\,\\mathrm{A}$ and $i_L(\\infty)=\\tfrac{8}{3}\\,\\mathrm{A}$, keeping $48/18$.",
        c: "$i_L(0^+)=2\\,\\mathrm{A}$, treating $6\\,\\Omega$ and $18\\,\\Omega$ as series before $t=0$.",
        d: "$i_L$ jumps to $0$ at $t=0^+$.",
      },
      answer: "a",
      why: "Before $t=0$, $L$ shorts the $18\\,\\Omega$, so $i_L(0^-)=48/6=8\\,\\mathrm{A}=i_L(0^+)$. After the source is gone, $i_L(\\infty)=0$ and $R_{Th}=18\\,\\Omega$.",
    },
    {
      id: "s3-s7",
      type: "schematic",
      difficulty: "medium",
      view: "s3-s7",
      prompt: "Which pair is correct for $i_L(0^+)$ and $\\tau$ after the switch opens?",
      options: {
        a: "$i_L(0^+)=2\\,\\mathrm{A}$ and $\\tau=0.5\\,\\mathrm{s}$",
        b: "$i_L(0^+)=6\\,\\mathrm{A}$ and $\\tau=1.5\\,\\mathrm{s}$",
        c: "$i_L(0^+)=6\\,\\mathrm{A}$ and $\\tau=0.5\\,\\mathrm{s}$",
        d: "$i_L(0^+)=0$ and $\\tau=0.5\\,\\mathrm{s}$",
      },
      answer: "c",
      why: "Before switching, $L$ is a DC short and the $8\\,\\Omega$ is bypassed, so $i_L(0^-)=24/4=6\\,\\mathrm{A}=i_L(0^+)$. After switching $R_{Th}=4+8=12\\,\\Omega$, so $\\tau=L/R_{Th}=6/12=0.5\\,\\mathrm{s}$.",
    },
    {
      id: "s3-s8",
      type: "schematic",
      difficulty: "harder",
      view: "s3-s8",
      prompt: "What is $i_L(t)$ for $t\\ge 0$?",
      options: {
        a: "$6e^{-2t}\\,\\mathrm{A}$",
        b: "$2+4e^{-2t}\\,\\mathrm{A}$",
        c: "$2\\bigl(1-e^{-2t}\\bigr)\\,\\mathrm{A}$",
        d: "$6+2e^{-2t}\\,\\mathrm{A}$",
      },
      answer: "b",
      why: "$i_L(0^+)=18/3=6\\,\\mathrm{A}$. $i_L(\\infty)=18/(3+6)=2\\,\\mathrm{A}$. $R_{Th}=9\\,\\Omega$, $\\tau=4.5/9=0.5\\,\\mathrm{s}$, so $e^{-t/\\tau}=e^{-2t}$. $i_L(t)=2+(6-2)e^{-2t}=2+4e^{-2t}\\,\\mathrm{A}$.",
    },
    {
      id: "s3-s9",
      type: "schematic",
      difficulty: "harder",
      view: "s3-s9",
      prompt: "Approximately what is $i_L$ at $t=1.0\\,\\mathrm{s}$?",
      options: {
        a: "$6.00\\,\\mathrm{A}$",
        b: "$4.00\\,\\mathrm{A}$",
        c: "$2.00\\,\\mathrm{A}$",
        d: "$2.54\\,\\mathrm{A}$",
      },
      answer: "d",
      why: "$i_L(0^+)=12/2=6\\,\\mathrm{A}$. $i_L(\\infty)=12/(2+4)=2\\,\\mathrm{A}$. $\\tau=3/(2+4)=0.5\\,\\mathrm{s}$. Therefore $i_L(1)=2+(6-2)e^{-1/0.5}=2+4e^{-2}=2.54\\,\\mathrm{A}$.",
    },
    {
      id: "s3-s10",
      type: "schematic",
      difficulty: "medium",
      view: "s3-s10",
      prompt: "Which pair is correct?",
      options: {
        a: "$i_L(0^+)=8\\,\\mathrm{A}$ and $i_L(\\infty)=2\\,\\mathrm{A}$",
        b: "$i_L(0^+)=2\\,\\mathrm{A}$ and $i_L(\\infty)=8\\,\\mathrm{A}$",
        c: "$i_L(0^+)=0$ and $i_L(\\infty)=2\\,\\mathrm{A}$",
        d: "$i_L(0^+)=8\\,\\mathrm{A}$ and $i_L(\\infty)=8\\,\\mathrm{A}$",
      },
      answer: "a",
      why: "Before switching, the $15\\,\\Omega$ is shorted and $L$ is a DC short, so $i_L(0^-)=40/5=8\\,\\mathrm{A}=i_L(0^+)$. After switching, $i_L(\\infty)=40/(5+15)=2\\,\\mathrm{A}$.",
    },
    {
      id: "s3-s11",
      type: "schematic",
      difficulty: "harder",
      view: "s3-s11",
      prompt:
        "The measured post-switch time constant is $0.5\\,\\mathrm{s}$. What is $R_x$?",
      options: {
        a: "$5\\,\\Omega$",
        b: "$10\\,\\Omega$",
        c: "$15\\,\\Omega$",
        d: "$20\\,\\Omega$",
      },
      answer: "c",
      why: "For $t>0$, $\\tau=L/R_{Th}=10/(5+R_x)=0.5$. Therefore $5+R_x=20\\,\\Omega$ and $R_x=15\\,\\Omega$.",
    },
    {
      id: "s3-s12",
      type: "schematic",
      difficulty: "harder",
      view: "s3-s12",
      prompt:
        "Which pair gives the energy stored in $L$ immediately after switching and at final DC steady state?",
      options: {
        a: "$6\\,\\mathrm{J}$ then $54\\,\\mathrm{J}$",
        b: "$54\\,\\mathrm{J}$ then $6\\,\\mathrm{J}$",
        c: "$18\\,\\mathrm{J}$ then $6\\,\\mathrm{J}$",
        d: "$54\\,\\mathrm{J}$ then $0\\,\\mathrm{J}$",
      },
      answer: "b",
      why: "$i_L(0^+)=24/4=6\\,\\mathrm{A}$, so $W(0^+)=\\tfrac12(3)(6)^2=54\\,\\mathrm{J}$. Final current is $24/(4+8)=2\\,\\mathrm{A}$, so $W(\\infty)=\\tfrac12(3)(2)^2=6\\,\\mathrm{J}$.",
    },
  ],
};

export function practiceForLab(labId) {
  return SECTION3_PRACTICE[labId] || [];
}
